// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANfnRJEPxJMjHv6_tTrthEC0LWV6RWvIM',
    appId: '1:68821595235:web:c7b437d84204b6c8bb7456',
    messagingSenderId: '68821595235',
    projectId: 'outq-2b5af',
    authDomain: 'outq-2b5af.firebaseapp.com',
    storageBucket: 'outq-2b5af.appspot.com',
    measurementId: 'G-001W70R81S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANlti_Sl3e6s0TwHWvPdvnuy1SxydUks0',
    appId: '1:68821595235:android:2226c0039166f3eabb7456',
    messagingSenderId: '68821595235',
    projectId: 'outq-2b5af',
    storageBucket: 'outq-2b5af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf32YRyLAVb7gbBDoqfvGzLNR8d-V317c',
    appId: '1:68821595235:ios:300c6f38ad37bd46bb7456',
    messagingSenderId: '68821595235',
    projectId: 'outq-2b5af',
    storageBucket: 'outq-2b5af.appspot.com',
    iosClientId:
        '68821595235-9vivlp3f1dqdjbe6beaot43baopj6l9q.apps.googleusercontent.com',
    iosBundleId: 'in.outq.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf32YRyLAVb7gbBDoqfvGzLNR8d-V317c',
    appId: '1:68821595235:ios:300c6f38ad37bd46bb7456',
    messagingSenderId: '68821595235',
    projectId: 'outq-2b5af',
    storageBucket: 'outq-2b5af.appspot.com',
    iosClientId:
        '68821595235-9vivlp3f1dqdjbe6beaot43baopj6l9q.apps.googleusercontent.com',
    iosBundleId: 'in.outq.app',
  );
}
